// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: enum_example.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_enum_5fexample_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_enum_5fexample_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3019000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3019004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_enum_5fexample_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_enum_5fexample_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_enum_5fexample_2eproto;
namespace example {
namespace enumerations {
class EnumMessage;
struct EnumMessageDefaultTypeInternal;
extern EnumMessageDefaultTypeInternal _EnumMessage_default_instance_;
}  // namespace enumerations
}  // namespace example
PROTOBUF_NAMESPACE_OPEN
template<> ::example::enumerations::EnumMessage* Arena::CreateMaybeMessage<::example::enumerations::EnumMessage>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace example {
namespace enumerations {

enum DayOfTheWeek : int {
  UNKNOWN = 0,
  MONDAY = 1,
  TUESDAY = 2,
  WEDNESDAY = 3,
  THURSDAY = 4,
  FRIDAY = 5,
  SATURDAY = 6,
  SUNDAY = 7,
  DayOfTheWeek_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  DayOfTheWeek_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool DayOfTheWeek_IsValid(int value);
constexpr DayOfTheWeek DayOfTheWeek_MIN = UNKNOWN;
constexpr DayOfTheWeek DayOfTheWeek_MAX = SUNDAY;
constexpr int DayOfTheWeek_ARRAYSIZE = DayOfTheWeek_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* DayOfTheWeek_descriptor();
template<typename T>
inline const std::string& DayOfTheWeek_Name(T enum_t_value) {
  static_assert(::std::is_same<T, DayOfTheWeek>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function DayOfTheWeek_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    DayOfTheWeek_descriptor(), enum_t_value);
}
inline bool DayOfTheWeek_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, DayOfTheWeek* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<DayOfTheWeek>(
    DayOfTheWeek_descriptor(), name, value);
}
// ===================================================================

class EnumMessage final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:example.enumerations.EnumMessage) */ {
 public:
  inline EnumMessage() : EnumMessage(nullptr) {}
  ~EnumMessage() override;
  explicit constexpr EnumMessage(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  EnumMessage(const EnumMessage& from);
  EnumMessage(EnumMessage&& from) noexcept
    : EnumMessage() {
    *this = ::std::move(from);
  }

  inline EnumMessage& operator=(const EnumMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline EnumMessage& operator=(EnumMessage&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const EnumMessage& default_instance() {
    return *internal_default_instance();
  }
  static inline const EnumMessage* internal_default_instance() {
    return reinterpret_cast<const EnumMessage*>(
               &_EnumMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(EnumMessage& a, EnumMessage& b) {
    a.Swap(&b);
  }
  inline void Swap(EnumMessage* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(EnumMessage* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  EnumMessage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<EnumMessage>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const EnumMessage& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const EnumMessage& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(EnumMessage* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "example.enumerations.EnumMessage";
  }
  protected:
  explicit EnumMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIdFieldNumber = 1,
    kDayOfTheWeekFieldNumber = 2,
  };
  // int32 id = 1;
  void clear_id();
  int32_t id() const;
  void set_id(int32_t value);
  private:
  int32_t _internal_id() const;
  void _internal_set_id(int32_t value);
  public:

  // .example.enumerations.DayOfTheWeek day_of_the_week = 2;
  void clear_day_of_the_week();
  ::example::enumerations::DayOfTheWeek day_of_the_week() const;
  void set_day_of_the_week(::example::enumerations::DayOfTheWeek value);
  private:
  ::example::enumerations::DayOfTheWeek _internal_day_of_the_week() const;
  void _internal_set_day_of_the_week(::example::enumerations::DayOfTheWeek value);
  public:

  // @@protoc_insertion_point(class_scope:example.enumerations.EnumMessage)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  int32_t id_;
  int day_of_the_week_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_enum_5fexample_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// EnumMessage

// int32 id = 1;
inline void EnumMessage::clear_id() {
  id_ = 0;
}
inline int32_t EnumMessage::_internal_id() const {
  return id_;
}
inline int32_t EnumMessage::id() const {
  // @@protoc_insertion_point(field_get:example.enumerations.EnumMessage.id)
  return _internal_id();
}
inline void EnumMessage::_internal_set_id(int32_t value) {
  
  id_ = value;
}
inline void EnumMessage::set_id(int32_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:example.enumerations.EnumMessage.id)
}

// .example.enumerations.DayOfTheWeek day_of_the_week = 2;
inline void EnumMessage::clear_day_of_the_week() {
  day_of_the_week_ = 0;
}
inline ::example::enumerations::DayOfTheWeek EnumMessage::_internal_day_of_the_week() const {
  return static_cast< ::example::enumerations::DayOfTheWeek >(day_of_the_week_);
}
inline ::example::enumerations::DayOfTheWeek EnumMessage::day_of_the_week() const {
  // @@protoc_insertion_point(field_get:example.enumerations.EnumMessage.day_of_the_week)
  return _internal_day_of_the_week();
}
inline void EnumMessage::_internal_set_day_of_the_week(::example::enumerations::DayOfTheWeek value) {
  
  day_of_the_week_ = value;
}
inline void EnumMessage::set_day_of_the_week(::example::enumerations::DayOfTheWeek value) {
  _internal_set_day_of_the_week(value);
  // @@protoc_insertion_point(field_set:example.enumerations.EnumMessage.day_of_the_week)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace enumerations
}  // namespace example

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::example::enumerations::DayOfTheWeek> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::example::enumerations::DayOfTheWeek>() {
  return ::example::enumerations::DayOfTheWeek_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_enum_5fexample_2eproto
